//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int idBooking { get; set; }
        public bool Status { get; set; }
        public int idClient { get; set; }
        public int idSession { get; set; }
        public int idSeat { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Seat Seat { get; set; }
        public virtual Session Session { get; set; }
    }
}
